/**
 * Content Hashing Script
 *
 * Runs after Vite build to hash content files for immutable caching:
 * 1. Read manifest (which already contains content hashes from Vite plugin)
 * 2. Copy files to dist/ with hashed names using manifest hashes
 * 3. Update manifest with hashed paths
 * 4. Hash the manifest itself
 * 5. Inject manifest hash into index.html
 *
 * Result: All content can be served with immutable, 1-year cache headers.
 * Only changed files get new URLs.
 */

import { createHash } from "node:crypto";
import {
  readdirSync,
  readFileSync,
  writeFileSync,
  existsSync,
  mkdirSync,
  copyFileSync,
} from "node:fs";
import { resolve, join } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const DIST = resolve(ROOT, "dist");
const CONTENT_DIR = resolve(ROOT, "content");
const CONTEXT_DIR = resolve(ROOT, "context");

/**
 * Generate a short content hash (8 chars)
 */
function hashContent(content: string): string {
  return createHash("sha256").update(content).digest("hex").slice(0, 8);
}

/**
 * Recursively process context files, computing hashes and copying with hashed names
 */
function processContextDirectory(
  sourceDir: string,
  destDir: string,
  relativePath = "",
): Array<{ original: string; path: string; hash: string }> {
  const results: Array<{ original: string; path: string; hash: string }> = [];

  if (!existsSync(sourceDir)) {
    return results;
  }

  const entries = readdirSync(sourceDir, { withFileTypes: true });

  for (const entry of entries) {
    const sourcePath = join(sourceDir, entry.name);
    const relPath = relativePath ? `${relativePath}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      // Ensure dest subdir exists
      const subDestDir = join(destDir, entry.name);
      mkdirSync(subDestDir, { recursive: true });

      // Recurse
      const subResults = processContextDirectory(
        sourcePath,
        subDestDir,
        relPath,
      );
      results.push(...subResults);
    } else if (entry.name.endsWith(".md")) {
      // Hash and copy markdown files
      const content = readFileSync(sourcePath, "utf-8");
      const hash = hashContent(content);
      const baseName = entry.name.replace(".md", "");
      const hashedName = `${baseName}.${hash}.md`;

      // Ensure destination directory exists
      const destSubDir = join(destDir, relativePath);
      mkdirSync(destSubDir, { recursive: true });

      const destPath = join(destSubDir, hashedName);
      writeFileSync(destPath, content);

      // Original path without .md extension (for URL matching)
      const originalPath = relativePath
        ? `${relativePath}/${baseName}`
        : baseName;
      const hashedPath = relativePath
        ? `${relativePath}/${hashedName}`
        : hashedName;

      results.push({
        original: originalPath,
        path: hashedPath,
        hash,
      });

      console.log(`  📄 ${originalPath}.md → ${hashedName}`);
    } else {
      // Copy non-markdown files as-is
      const destSubDir = join(destDir, relativePath);
      mkdirSync(destSubDir, { recursive: true });
      const destPath = join(destSubDir, entry.name);
      copyFileSync(sourcePath, destPath);
    }
  }

  return results;
}

/**
 * Main build process
 */
async function main() {
  console.log("\n🔐 Hashing content files...\n");

  // Read the manifest generated by Vite (has hashes but unhashed paths)
  const sourceManifestPath = resolve(DIST, "content/manifest.json");
  if (!existsSync(sourceManifestPath)) {
    console.error("❌ No manifest found at dist/content/manifest.json");
    console.error("   Make sure vite build ran first.");
    process.exit(1);
  }

  const manifest = JSON.parse(readFileSync(sourceManifestPath, "utf-8"));

  // Ensure dist directories exist
  const distArticles = resolve(DIST, "content/articles");
  const distContext = resolve(DIST, "context");
  mkdirSync(distArticles, { recursive: true });
  mkdirSync(distContext, { recursive: true });

  // Process articles - use hashes from manifest
  console.log("📁 Processing articles...");
  const updatedArticles = [];

  for (const article of manifest.articles) {
    const sourceFile = resolve(CONTENT_DIR, "articles", `${article.id}.md`);
    if (!existsSync(sourceFile)) {
      console.warn(`  ⚠️  Source not found: ${article.id}.md`);
      continue;
    }

    const content = readFileSync(sourceFile, "utf-8");
    const hashedName = `${article.id}.${article.hash}.md`;
    const destPath = resolve(distArticles, hashedName);

    writeFileSync(destPath, content);
    console.log(`  📄 ${article.id}.md → ${hashedName}`);

    updatedArticles.push({
      ...article,
      path: `articles/${hashedName}`,
    });
  }

  // Process context files
  console.log("\n📁 Processing context...");
  const contextFiles = processContextDirectory(CONTEXT_DIR, distContext);

  // Build final manifest with hashed paths
  const finalManifest = {
    version: 1,
    generatedAt: new Date().toISOString(),
    articles: updatedArticles,
    context: contextFiles,
  };

  // Hash the manifest itself
  const manifestJson = JSON.stringify(finalManifest, null, 2);
  const manifestHash = hashContent(manifestJson);
  const manifestFileName = `manifest.${manifestHash}.json`;

  // Write hashed manifest
  const manifestPath = resolve(DIST, "content", manifestFileName);
  writeFileSync(manifestPath, manifestJson);
  console.log(`\n📋 Manifest: ${manifestFileName}`);

  // Update index.html with manifest path
  console.log("\n📝 Updating index.html...");
  const indexPath = resolve(DIST, "index.html");
  let indexHtml = readFileSync(indexPath, "utf-8");

  // Inject manifest path as a global variable
  const manifestScript = `<script>window.__MANIFEST_PATH__="/content/${manifestFileName}";</script>`;

  // Insert before closing </head> tag
  if (indexHtml.includes("</head>")) {
    indexHtml = indexHtml.replace("</head>", `${manifestScript}\n</head>`);
  } else {
    // Fallback: insert at start of body
    indexHtml = indexHtml.replace("<body>", `<body>\n${manifestScript}`);
  }

  writeFileSync(indexPath, indexHtml);
  console.log(`  ✅ Injected manifest path: /content/${manifestFileName}`);

  // Summary
  console.log("\n✨ Content hashing complete!");
  console.log(`   Articles: ${updatedArticles.length}`);
  console.log(`   Context files: ${contextFiles.length}`);
  console.log(`   Manifest: ${manifestFileName}\n`);
}

main().catch((err) => {
  console.error("❌ Error:", err);
  process.exit(1);
});
