/**
 * Content Hashing Script
 *
 * Runs after Vite build to hash content for immutable caching:
 * 1. Copy content JSON from public/ to dist/ (already generated by export scripts)
 * 2. Hash context files (leadership docs)
 * 3. Create hashed manifest
 * 4. Inject manifest path into index.html
 */

import { createHash } from "node:crypto";
import {
  readdirSync,
  readFileSync,
  writeFileSync,
  existsSync,
  mkdirSync,
  copyFileSync,
  rmSync,
} from "node:fs";
import { resolve, join } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const DIST = resolve(ROOT, "dist");
const PUBLIC = resolve(ROOT, "public");
const CONTEXT_DIR = resolve(ROOT, "context");

function hashContent(content: string): string {
  return createHash("sha256").update(content).digest("hex").slice(0, 8);
}

/**
 * Copy directory contents recursively
 */
function copyDir(src: string, dest: string) {
  if (!existsSync(src)) return;
  mkdirSync(dest, { recursive: true });

  for (const entry of readdirSync(src, { withFileTypes: true })) {
    const srcPath = join(src, entry.name);
    const destPath = join(dest, entry.name);

    if (entry.isDirectory()) {
      copyDir(srcPath, destPath);
    } else {
      copyFileSync(srcPath, destPath);
    }
  }
}

/**
 * Process context files with hashed names
 */
function processContextDirectory(
  sourceDir: string,
  destDir: string,
  relativePath = "",
): Array<{ original: string; path: string; hash: string }> {
  const results: Array<{ original: string; path: string; hash: string }> = [];

  if (!existsSync(sourceDir)) return results;

  for (const entry of readdirSync(sourceDir, { withFileTypes: true })) {
    const sourcePath = join(sourceDir, entry.name);
    const relPath = relativePath ? `${relativePath}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      const subDestDir = join(destDir, entry.name);
      mkdirSync(subDestDir, { recursive: true });
      results.push(...processContextDirectory(sourcePath, subDestDir, relPath));
    } else if (entry.name.endsWith(".md")) {
      const content = readFileSync(sourcePath, "utf-8");
      const hash = hashContent(content);
      const baseName = entry.name.replace(".md", "");
      const hashedName = `${baseName}.${hash}.md`;

      writeFileSync(join(destDir, hashedName), content);

      const originalPath = relativePath
        ? `${relativePath}/${baseName}`
        : baseName;
      const hashedPath = relativePath
        ? `${relativePath}/${hashedName}`
        : hashedName;

      results.push({ original: originalPath, path: hashedPath, hash });
      console.log(`  📄 ${originalPath}.md → ${hashedName}`);
    } else {
      copyFileSync(sourcePath, join(destDir, entry.name));
    }
  }

  return results;
}

async function main() {
  console.log("\n🔐 Hashing content files...\n");

  // Copy content from public/ to dist/ (Vite already does this, but ensure it's there)
  console.log("📁 Copying content...");
  copyDir(resolve(PUBLIC, "content"), resolve(DIST, "content"));
  copyDir(resolve(PUBLIC, "bookmarks"), resolve(DIST, "bookmarks"));
  console.log("  ✅ Content, bookmarks copied");

  // Process context files with hashing
  console.log("\n📁 Processing context...");
  const distContext = resolve(DIST, "context");
  if (existsSync(distContext)) {
    rmSync(distContext, { recursive: true });
  }
  mkdirSync(distContext, { recursive: true });
  const contextFiles = processContextDirectory(CONTEXT_DIR, distContext);

  // Read content manifest (articles, drafts, projects)
  const contentManifestPath = resolve(DIST, "content", "manifest.json");
  const contentManifest = existsSync(contentManifestPath)
    ? JSON.parse(readFileSync(contentManifestPath, "utf-8"))
    : { articles: [], drafts: [], projects: [] };

  // Build final manifest - preserve the full structure
  const finalManifest = {
    version: 1,
    articles: contentManifest.articles || [],
    drafts: contentManifest.drafts || [],
    projects: contentManifest.projects || [],
    context: contextFiles,
  };

  const manifestJson = JSON.stringify(finalManifest, null, 2);
  const manifestHash = hashContent(manifestJson);
  const manifestFileName = `manifest.${manifestHash}.json`;

  writeFileSync(resolve(DIST, "content", manifestFileName), manifestJson);
  console.log(`\n📋 Manifest: ${manifestFileName}`);

  // Inject manifest path into index.html
  console.log("\n📝 Updating index.html...");
  const indexPath = resolve(DIST, "index.html");
  let indexHtml = readFileSync(indexPath, "utf-8");

  const manifestScript = `<script>window.__MANIFEST_PATH__="/content/${manifestFileName}";</script>`;
  indexHtml = indexHtml.replace(
    /<script>window\.__MANIFEST_PATH__="[^"]*";<\/script>\n?/g,
    "",
  );

  if (indexHtml.includes("</head>")) {
    indexHtml = indexHtml.replace("</head>", `${manifestScript}\n</head>`);
  } else {
    indexHtml = indexHtml.replace("<body>", `<body>\n${manifestScript}`);
  }

  writeFileSync(indexPath, indexHtml);
  console.log(`  ✅ Injected manifest path`);

  console.log("\n✨ Done!");
  console.log(`   Articles: ${finalManifest.articles.length}`);
  console.log(`   Drafts: ${finalManifest.drafts.length}`);
  console.log(`   Projects: ${finalManifest.projects.length}`);
  console.log(`   Context: ${contextFiles.length}\n`);
}

main().catch((err) => {
  console.error("❌ Error:", err);
  process.exit(1);
});
